# Generated by Django 3.2.6 on 2022-05-23 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=500)),
                ('cash', models.CharField(default=10000, max_length=50)),
                ('real_cash', models.CharField(default=0, max_length=50)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leagues.league')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
