# Generated by Django 3.2.6 on 2022-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cash',
            field=models.CharField(default=10000, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='real_cash',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
