# Generated by Django 3.2.6 on 2022-03-19 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
    ]
