# Generated by Django 3.2.6 on 2022-03-19 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_rename_team_name_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
    ]
