# Generated by Django 3.2.6 on 2022-04-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='id',
            new_name='team_id',
        ),
    ]
