# Generated by Django 3.2.6 on 2022-04-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('bul_calendar', '0001_initial'),
        ('teams', '0004_rename_name_team_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a_set', to='teams.team'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_set', to='teams.team'),
        ),
    ]
