# Generated by Django 3.2.6 on 2022-04-02 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('bul_calendar', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
