# Generated by Django 3.2.6 on 2022-04-22 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_team_a', to='teams.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_team_b', to='teams.team')),
            ],
        ),
    ]
