# Generated by Django 3.2.6 on 2022-05-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_team_a', to='teams.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_team_b', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=1024)),
                ('team_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_team_a', to='teams.team')),
                ('team_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_team_b', to='teams.team')),
            ],
        ),
    ]
