# Generated by Django 3.2.6 on 2022-05-10 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0002_friends_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=1024)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
