# Generated by Django 3.2.6 on 2022-05-15 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20220430_1328'),
        ('friends', '0003_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_a',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_b',
        ),
        migrations.AddField(
            model_name='chat',
            name='team_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_team_a', to='teams.team'),
        ),
        migrations.AddField(
            model_name='chat',
            name='team_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_team_b', to='teams.team'),
        ),
    ]
