# Generated by Django 3.2.6 on 2022-05-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_full', models.BooleanField(default=False)),
                ('num_of_teams', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
