# Generated by Django 3.2.6 on 2022-04-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='VAL',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='assists',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='blocks_against',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='blocks_for',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='defensive_reb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='dunks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='fouls_against',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='fouls_for',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='games',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='height',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='offensive_reb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='p1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='p11',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='p12',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='p2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='p21',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='p22',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='p3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='p31',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='p32',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='pic',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='plusminus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='pts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='steals',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='total_reb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='turnovers',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='player_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='team_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
