# Generated by Django 3.2.6 on 2022-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_is_first_five'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(default='', max_length=50)),
                ('price', models.CharField(default=0, max_length=50)),
                ('pack_type', models.CharField(default='Normal', max_length=50)),
                ('pack_image', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
