# Generated by Django 3.2.6 on 2022-05-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('pic', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('games', models.PositiveSmallIntegerField()),
                ('pts', models.FloatField()),
                ('p21', models.FloatField()),
                ('p22', models.FloatField()),
                ('p31', models.FloatField()),
                ('p32', models.FloatField()),
                ('p11', models.FloatField()),
                ('p12', models.FloatField()),
                ('p2', models.FloatField()),
                ('p3', models.FloatField()),
                ('p1', models.FloatField()),
                ('defensive_reb', models.FloatField()),
                ('offensive_reb', models.FloatField()),
                ('total_reb', models.FloatField()),
                ('fouls_against', models.FloatField()),
                ('fouls_for', models.FloatField()),
                ('steals', models.FloatField()),
                ('turnovers', models.FloatField()),
                ('assists', models.FloatField()),
                ('blocks_for', models.FloatField()),
                ('blocks_against', models.FloatField()),
                ('VAL', models.FloatField()),
                ('plusminus', models.FloatField()),
                ('dunks', models.FloatField()),
            ],
        ),
    ]
